# Generated by Django 4.2.1 on 2023-05-12 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='info',
            field=models.TextField(default='No information available'),
        ),
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.CharField(default='John', max_length=255),
        ),
        migrations.AddField(
            model_name='profile',
            name='surname',
            field=models.CharField(default='Doe', max_length=255),
        ),
    ]
