# Generated by Django 4.2.1 on 2023-05-15 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_profile_followers_profile_following'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='default_image.jpg', upload_to='profile_images'),
        ),
    ]
